### ISSUE TITLE
llac在bds1.19.50llbds2.9beta上引起崩溃

### ISSUE THREAD

**Issue by zevlaoxie2010** [LiteLDev/LLAntiCheat-release#5]
崩溃日志
[Crashed!]
-- Unhandled Exception in -> LLAntiCheat_pr30_fix5.dll
-- Exception Code: 0xC0000005
-- Minidump generated in Directory ./logs/Crash

[StackTrace] Function onPostInit at 0x7FFF7978BD00  [LLAntiCheat_pr30_fix5.dll]
[StackTrace] Function ServerNetworkHandler::createNewPlayer at 0x7FF7D01668E0  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function VanillaServerNetworkHandler::handle at 0x7FF7CFDCDDB0  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function Packet::handle at 0x7FF7D0439EE0  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function NetworkHandler::_sortAndPacketizeEvents at 0x7FF7D0148B10  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function <lambda_9d99988d1ae27229e5cb75de5d8fd242>::operator() at 0x7FF7D0147380  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function NetworkHandler::runEvents at 0x7FF7D014AEF0  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function Minecraft::update at 0x7FF7D05A0E60  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function ServerInstance::_update at 0x7FF7D05A7280  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function <lambda_9c72527c89bc5df41fe482e4153a365f>::operator() at 0x7FF7D05A55A0  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_9c72527c89bc5df41fe482e4153a365f> >,0> at 0x7FF7D05A27E0  [bedrock_server_mod.exe<1.19.50.02>]
[StackTrace] Function o__realloc_base at 0x7FFF8229F440  [ucrtbase.DLL<10.0.14393.2990>]
[StackTrace] Function BaseThreadInitThunk at 0x7FFF966F13B0  [KERNEL32.DLL<6.3.9600.20625>]
[StackTrace] Function RtlUserThreadStart at 0x7FFF989B54D0  [ntdll.dll<6.3.9600.20512>]

玩家加入游戏后会产生崩溃
llbds测试版本
https://github.com/LiteLDev/LiteLoaderBDS/actions/runs/3613959913

**Comment by mikhaillav** [comment]
u need to use this version:
https://5g8svn-my.sharepoint.com/:u:/g/personal/shrbox_litebds_com/EX6v-VmuLClIuAjhmRxFsc4BB38d8Xej9wAtOEMjt6KRpw?e=zJ0obh
